#!/usr/bin/env bash
# Pings a given IP address 5 times to check if the host is on the network
if [ $# -ne 1 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"