#!/user/bin/bash#!/usr/bin/env bash
# localhost is 127.0.0.2 and facebook.com is 8.8.8.8
echo "Updating the /etc/hosts file..."
{
    echo "127.0.0.2   localhost"
    echo "8.8.8.8     facebook.com"
} | sudo tee -a /etc/hosts